apiVersion: v1
kind: Pod
metadata:
  name: template
  labels:
    type: backend
    name: template
    app: hello-pod
spec:
  containers:
  - name: template
    image: yasindeger48/template:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9090
