
services:
  jenkins:
    build: ../../../DevOps Bootcamp/Projects/DevOps-Automation-Pipelines/k8s-own/jenkins  # Building with Dockerfile
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - test_network

  selenium-hub:
    image: selenium/hub:4.20.0-20240425
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - test_network

  chrome-node1:
    image: selenium/node-chrome:4.20.0-20240425
    container_name: chrome-node1
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    networks:
      - test_network

  chrome-node2:
    image: selenium/node-chrome:4.20.0-20240425
    container_name: chrome-node2
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    networks:
      - test_network

volumes:
  jenkins_home:

networks:
  test_network:
    driver: bridge