apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.20.0-20240425
          ports:
            - containerPort: 4442
            - containerPort: 4443
            - containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-service
spec:
  ports:
    - port: 4444
      targetPort: 4444
  selector:
    app: selenium-hub

