apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXNfdXNlcg==   # postgres_user base64 encoded
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=   # postgres_password base64 encoded
