apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  # Nginx'in 3 kopyası çalışacak
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21  # Çalışacak Nginx image versiyonu
          ports:
            - containerPort: 80  # Nginx container'ındaki port
