apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
        - name: mysite-container
          image: yasindeger48/sitelast
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-service
spec:
  type: NodePort
  selector:
    app: mysite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
